name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: actions/checkout@master
      with:
        repository: ''
        ref: ''
        token: ''
        ssh-key: ''
        ssh-known-hosts: ''
        ssh-strict: ''
        persist-credentials: ''
        path: ''
        clean: ''
        fetch-depth: ''
        lfs: ''
        submodules: ''
      
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
          cd /var/www/
          git pull origin master
